import React from 'react';
import { Shield, Mail, MapPin, User } from 'lucide-react';

function PrivacyPolicy() {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="text-center mb-16">
        <h1 className="text-4xl font-bold text-gray-800 dark:text-white mb-4">
          Privacy Policy
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-300">
          Last updated: July 27, 2025
        </p>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-8 mb-10 border border-gray-100 dark:border-gray-700">
        <p className="text-gray-600 dark:text-gray-300 mb-6 leading-relaxed">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-8 mb-10 border border-gray-100 dark:border-gray-700">
        <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-6 flex items-center">
          <Shield className="text-orange-500 mr-3" size={24} />
          Interpretation and Definitions
        </h2>
        <div className="prose prose-lg text-gray-600 dark:text-gray-300 max-w-none">
          <h3 className="text-xl font-semibold text-gray-700 dark:text-white">Interpretation</h3>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          <h3 className="text-xl font-semibold text-gray-700 dark:text-white mt-6">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to ChemistryForum.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: India</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Website</strong> refers to ChemistryForum, accessible from [Your Website URL]</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </div>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-8 mb-10 border border-gray-100 dark:border-gray-700">
        <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-6">Information We Collect</h2>
        <p className="text-gray-600 dark:text-gray-300 mb-4">We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, and in connection with other activities, services, features or resources we make available on our Site.</p>
        <p className="text-gray-600 dark:text-gray-300">Users may be asked for, as appropriate, name, email address. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.</p>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-8 mb-10 border border-gray-100 dark:border-gray-700">
        <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-6">How We Use Your Information</h2>
        <p className="text-gray-600 dark:text-gray-300">ChemistryForum may collect and use Users personal information for the following purposes:</p>
        <ul className="list-disc list-inside text-gray-600 dark:text-gray-300">
          <li className="mb-2">To improve customer service</li>
          <li className="mb-2">To personalize user experience</li>
          <li className="mb-2">To improve our Site</li>
          <li className="mb-2">To run a promotion, contest, survey or other Site feature</li>
          <li>To send periodic emails</li>
        </ul>
      </div>
      
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-8 mb-10 border border-gray-100 dark:border-gray-700">
        <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-6">Changes to This Privacy Policy</h2>
        <p className="text-gray-600 dark:text-gray-300">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
        <p className="text-gray-600 dark:text-gray-300 mt-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-8 border border-gray-100 dark:border-gray-700">
        <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-6">Contact Us</h2>
        <p className="text-gray-600 dark:text-gray-300 mb-6">If you have any questions about this Privacy Policy, You can contact us:</p>
        <div className="space-y-4">
          <div className="flex items-start">
            <div className="bg-orange-100 dark:bg-orange-900/20 p-3 rounded-full mr-4">
              <User className="text-orange-500" size={20} />
            </div>
            <div>
              <h3 className="font-semibold text-gray-800 dark:text-white">Name</h3>
              <p className="text-gray-600 dark:text-gray-300">Nitish Kumar Singh</p>
            </div>
          </div>
          <div className="flex items-start">
            <div className="bg-orange-100 dark:bg-orange-900/20 p-3 rounded-full mr-4">
              <Mail className="text-orange-500" size={20} />
            </div>
            <div>
              <h3 className="font-semibold text-gray-800 dark:text-white">Email</h3>
              <a href="mailto:nitishkumarsingh1@gmail.com" className="text-orange-500 hover:underline">nitishkumarsingh1@gmail.com</a>
            </div>
          </div>
          <div className="flex items-start">
            <div className="bg-orange-100 dark:bg-orange-900/20 p-3 rounded-full mr-4">
              <MapPin className="text-orange-500" size={20} />
            </div>
            <div>
              <h3 className="font-semibold text-gray-800 dark:text-white">Address</h3>
              <p className="text-gray-600 dark:text-gray-300">Ground Floor, VIM-65, Phase-VII, Rangeswar Nagar, Sailashree Vihar, Patia, Bhubaneswar, Odisha 751021</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default PrivacyPolicy;
